# Minute Scaraping
name: world-pop-scraping

# Control when the action will run 
on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: main
    
# Setup Job Environment
jobs:
  build-deploy:
    runs-on: macos-latest
    permissions:
      contents: write
      
    # Load Repo & install R
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-pandoc@v2

    # Setup R
    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'

    # Setup Quarto
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    # Install R Packages
    - name: Install Packages
      run: |
        R -e 'install.packages("tidyverse")'
        R -e 'install.packages("rmarkdown")'
        R -e 'install.packages("pandoc")'
        R -e 'install.packages("janitor")'
        R -e 'install.packages("rvest")'
        R -e 'install.packages("cowplot")'
        R -e 'install.packages("plotly")'
        R -e 'install.packages("crosstalk")'
        R -e 'install.packages("DT")'

    # Run Script
    # RMarkdown
    #- name: Scrape World Pop
      #run: Rscript -e 'rmarkdown::render(input = "index.Rmd", output_format = "html_document")'
    
    # Quarto
    - name: Render World Pop
      uses: quarto-dev/quarto-actions/render@v2
      with:
        to: html
    
    - name: Publish HTML File
        uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
    
    - name: Commit results
      run: |
        git config --local user.name renan-peres
        git config --local user.email "renanmogo@protonmail.com"
        git commit index.html -m 'Re-build index.html'
        git push origin
    
